name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: uv sync

    - name: Format check
      run: uv run ruff format --check src/ tests/

    - name: Lint
      run: uv run ruff check src/ tests/

    - name: Type check
      run: uv run mypy src/

    - name: Test
      run: uv run pytest tests/