name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: uv sync --dev
    - name: Run pre-commit
      env:
        # Test environment variables for pre-commit hooks that might import code
        DISCORD_BOT_TOKEN: "test_token"
        DISCORD_GUILD_ID: "123456789"
        GEMINI_API_KEY: "test_api_key"
        OBSIDIAN_VAULT_PATH: "/tmp/test_vault"
        CHANNEL_INBOX: "123456789"
        CHANNEL_VOICE: "123456789"
        CHANNEL_FILES: "123456789"
        CHANNEL_MONEY: "123456789"
        CHANNEL_FINANCE_REPORTS: "123456789"
        CHANNEL_TASKS: "123456789"
        CHANNEL_PRODUCTIVITY_REVIEWS: "123456789"
        CHANNEL_NOTIFICATIONS: "123456789"
        CHANNEL_COMMANDS: "123456789"
        ENVIRONMENT: "test"
        ENABLE_MOCK_MODE: "true"
      uses: pre-commit/action@v3.0.1

  test:
    runs-on: ubuntu-latest
    needs: pre-commit

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: uv sync --dev

    - name: Test
      env:
        # Test environment variables
        DISCORD_BOT_TOKEN: "test_token"
        DISCORD_GUILD_ID: "123456789"
        GEMINI_API_KEY: "test_api_key"
        OBSIDIAN_VAULT_PATH: "/tmp/test_vault"
        CHANNEL_INBOX: "123456789"
        CHANNEL_VOICE: "123456789"
        CHANNEL_FILES: "123456789"
        CHANNEL_MONEY: "123456789"
        CHANNEL_FINANCE_REPORTS: "123456789"
        CHANNEL_TASKS: "123456789"
        CHANNEL_PRODUCTIVITY_REVIEWS: "123456789"
        CHANNEL_NOTIFICATIONS: "123456789"
        CHANNEL_COMMANDS: "123456789"
        ENVIRONMENT: "test"
        ENABLE_MOCK_MODE: "true"
      run: uv run pytest tests/
